package com.confia.shared.security.token;

import static com.confia.shared.security.token.JwsFixtures.CURRENT_KID;
import static com.confia.shared.security.token.JwsFixtures.PREVIOUS_KID;
import static com.confia.shared.security.token.JwsFixtures.issuedToken;
import static com.confia.shared.security.token.JwsFixtures.newPair;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.nio.charset.StandardCharsets;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.core.env.MapPropertySource;
import org.springframework.core.env.StandardEnvironment;

/**
 * The key ring loaded from the process environment (session-tokens-and-web-layer design.md,
 * decision 3; specs/identity, I78 to I80). Every key is generated by the test at run time and never
 * written anywhere (CLAUDE.md, regla 13). A failure must name the property, repeat no part of any
 * value and chain no cause: the decoder's own message can carry a fragment of its input (regla 11).
 */
class SigningKeyRingTest {

    private static final String CURRENT_KID_PROPERTY = "confia.security.admin-signing.current.kid";
    private static final String CURRENT_PRIVATE_PROPERTY =
            "confia.security.admin-signing.current.private-key";
    private static final String CURRENT_PUBLIC_PROPERTY =
            "confia.security.admin-signing.current.public-key";
    private static final String PREVIOUS_KID_PROPERTY = "confia.security.admin-signing.previous.kid";
    private static final String PREVIOUS_PRIVATE_PROPERTY =
            "confia.security.admin-signing.previous.private-key";
    private static final String PREVIOUS_PUBLIC_PROPERTY =
            "confia.security.admin-signing.previous.public-key";

    /** Unlike any word a message of the loader may write, and not a secret: invalid by construction. */
    private static final String NOT_BASE64 = "Tf8%Hd3^Vb6&Nc1*";

    @Test
    void aRingWithOnlyTheCurrentKeyLoadsAndSigns() {
        KeyPair current = newPair();

        SigningKeyRing ring = SigningKeyRing.fromEnvironment(environment(currentOnly(current)));

        assertThat(ring.signingKey().kid()).isEqualTo(CURRENT_KID);
        assertThat(ring.signingKey().hasPrivateKey()).isTrue();
        assertThat(ring.signingKey().publicKey()).isEqualTo(current.getPublic());
        assertThat(ring.keyForHeaderSegment(ring.currentHeaderSegment())).isPresent();
        CompactJws jws = new CompactJws(ring);
        assertThat(jws.verify(jws.sign(utf8("{\"a\":1}"))).kid()).isEqualTo(CURRENT_KID);
    }

    @Test
    void theCurrentKeySignsAndBothKeysVerify() {
        KeyPair current = newPair();
        KeyPair previous = newPair();
        SigningKeyRing ring = SigningKeyRing.fromEnvironment(
                environment(withPrevious(currentOnly(current), previous)));
        CompactJws jws = new CompactJws(ring);
        String signedBeforeRotation = issuedToken(PREVIOUS_KID, "{\"n\":1}", previous.getPrivate());

        String signedNow = jws.sign(utf8("{\"n\":2}"));

        assertThat(jws.verify(signedNow).kid()).isEqualTo(CURRENT_KID);
        assertThat(jws.verify(signedBeforeRotation).kid()).isEqualTo(PREVIOUS_KID);
    }

    @Test
    void retiringThePreviousKeyInvalidatesItsTokens() {
        KeyPair current = newPair();
        KeyPair previous = newPair();
        String signedWithPrevious = issuedToken(PREVIOUS_KID, "{\"n\":1}", previous.getPrivate());
        CompactJws withPrevious = new CompactJws(SigningKeyRing.fromEnvironment(
                environment(withPrevious(currentOnly(current), previous))));
        CompactJws afterRetiring = new CompactJws(SigningKeyRing.fromEnvironment(
                environment(currentOnly(current))));

        assertThat(withPrevious.verify(signedWithPrevious).kid()).isEqualTo(PREVIOUS_KID);
        assertThatThrownBy(() -> afterRetiring.verify(signedWithPrevious))
                .isInstanceOfSatisfying(TokenRejectedException.class,
                        e -> assertThat(e.rejection()).isEqualTo(TokenRejection.UNKNOWN_HEADER));
    }

    @ParameterizedTest
    @ValueSource(strings = {CURRENT_KID_PROPERTY, CURRENT_PRIVATE_PROPERTY, CURRENT_PUBLIC_PROPERTY})
    void aMissingRequiredPropertyIsNamed(String property) {
        Map<String, String> properties = currentOnly(newPair());
        properties.remove(property);

        assertRejectedNaming(properties, property, "");
    }

    @ParameterizedTest
    @ValueSource(strings = {CURRENT_KID_PROPERTY, CURRENT_PRIVATE_PROPERTY, CURRENT_PUBLIC_PROPERTY})
    void aBlankRequiredPropertyIsTreatedAsMissing(String property) {
        Map<String, String> properties = currentOnly(newPair());
        properties.put(property, "   ");

        assertRejectedNaming(properties, property, "");
    }

    @ParameterizedTest
    @ValueSource(strings = {CURRENT_PRIVATE_PROPERTY, CURRENT_PUBLIC_PROPERTY})
    void aValueThatIsNotBase64IsRejectedWithoutEchoingAnyPartOfIt(String property) {
        Map<String, String> properties = currentOnly(newPair());
        properties.put(property, NOT_BASE64);

        assertRejectedNaming(properties, property, NOT_BASE64);
    }

    @ParameterizedTest
    @ValueSource(strings = {CURRENT_PRIVATE_PROPERTY, CURRENT_PUBLIC_PROPERTY})
    void validBase64ThatIsNotAKeyIsRejectedWithoutEchoingAnyPartOfIt(String property) {
        Map<String, String> properties = currentOnly(newPair());
        String notAKey = Base64.getEncoder().encodeToString(
                utf8("this is certainly not a DER encoded key"));
        properties.put(property, notAKey);

        assertRejectedNaming(properties, property, notAKey);
    }

    @Test
    void anEd448PrivateKeyIsRejectedNamingThePropertyAndNeverEchoingIt() throws Exception {
        KeyPair ed448 = KeyPairGenerator.getInstance("Ed448").generateKeyPair();
        Map<String, String> properties = currentOnly(newPair());
        String privateKey = Base64.getEncoder().encodeToString(ed448.getPrivate().getEncoded());
        properties.put(CURRENT_PRIVATE_PROPERTY, privateKey);

        assertRejectedNaming(properties, CURRENT_PRIVATE_PROPERTY, privateKey);
    }

    @Test
    void anEd448PublicKeyIsRejectedNamingTheProperty() throws NoSuchAlgorithmException {
        KeyPair ed448 = KeyPairGenerator.getInstance("Ed448").generateKeyPair();
        Map<String, String> properties = currentOnly(newPair());
        String publicKey = Base64.getEncoder().encodeToString(ed448.getPublic().getEncoded());
        properties.put(CURRENT_PUBLIC_PROPERTY, publicKey);

        assertRejectedNaming(properties, CURRENT_PUBLIC_PROPERTY, publicKey);
    }

    @Test
    void aPairWhosePublicKeyDoesNotMatchThePrivateKeyIsDetectedBySigningAndVerifying() {
        Map<String, String> properties = currentOnly(newPair());
        properties.put(CURRENT_PUBLIC_PROPERTY, encode(newPair().getPublic().getEncoded()));

        assertThatThrownBy(() -> SigningKeyRing.fromEnvironment(environment(properties)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(CURRENT_PUBLIC_PROPERTY)
                .hasMessageContaining(CURRENT_PRIVATE_PROPERTY)
                .hasNoCause();
    }

    @ParameterizedTest
    @ValueSource(strings = {"", "a b", "a\"b", "a/b", "kéy", "kid\n"})
    void aCurrentKidOutsideTheClosedFormatIsRejectedWithoutEchoingIt(String kid) {
        Map<String, String> properties = currentOnly(newPair());
        properties.put(CURRENT_KID_PROPERTY, kid);

        assertThatThrownBy(() -> SigningKeyRing.fromEnvironment(environment(properties)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(CURRENT_KID_PROPERTY)
                .hasNoCause();
    }

    @Test
    void aKidOfSixtyFiveCharactersIsRejectedAndOneOfSixtyFourIsAccepted() {
        Map<String, String> tooLong = currentOnly(newPair());
        tooLong.put(CURRENT_KID_PROPERTY, "k".repeat(65));
        Map<String, String> longest = currentOnly(newPair());
        longest.put(CURRENT_KID_PROPERTY, "k".repeat(64));

        assertThatThrownBy(() -> SigningKeyRing.fromEnvironment(environment(tooLong)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(CURRENT_KID_PROPERTY)
                .hasMessageNotContaining("kkkk")
                .hasNoCause();
        assertThat(SigningKeyRing.fromEnvironment(environment(longest)).signingKey().kid())
                .hasSize(64);
    }

    @Test
    void aPreviousKidOutsideTheClosedFormatIsRejectedNamingThePreviousKidProperty() {
        Map<String, String> properties = withPrevious(currentOnly(newPair()), newPair());
        properties.put(PREVIOUS_KID_PROPERTY, "bad kid");

        assertThatThrownBy(() -> SigningKeyRing.fromEnvironment(environment(properties)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(PREVIOUS_KID_PROPERTY)
                .hasMessageNotContaining("bad kid")
                .hasNoCause();
    }

    @Test
    void aPreviousKidEqualToTheCurrentOneIsRejected() {
        Map<String, String> properties = withPrevious(currentOnly(newPair()), newPair());
        properties.put(PREVIOUS_KID_PROPERTY, CURRENT_KID);

        assertThatThrownBy(() -> SigningKeyRing.fromEnvironment(environment(properties)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(PREVIOUS_KID_PROPERTY)
                .hasMessageContaining(CURRENT_KID_PROPERTY)
                .hasNoCause();
    }

    @Test
    void aPreviousPublicKeyEqualToTheCurrentOneIsRejected() {
        KeyPair current = newPair();
        Map<String, String> properties = currentOnly(current);
        properties.put(PREVIOUS_KID_PROPERTY, PREVIOUS_KID);
        properties.put(PREVIOUS_PUBLIC_PROPERTY, encode(current.getPublic().getEncoded()));

        assertThatThrownBy(() -> SigningKeyRing.fromEnvironment(environment(properties)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(PREVIOUS_PUBLIC_PROPERTY)
                .hasMessageContaining(CURRENT_PUBLIC_PROPERTY)
                .hasNoCause();
    }

    @Test
    void aPreviousKidWithoutItsPublicKeyIsRejected() {
        Map<String, String> properties = currentOnly(newPair());
        properties.put(PREVIOUS_KID_PROPERTY, PREVIOUS_KID);

        assertRejectedNaming(properties, PREVIOUS_PUBLIC_PROPERTY, "");
    }

    @Test
    void aPreviousPublicKeyWithoutItsKidIsRejectedInsteadOfBeingSilentlyIgnored() {
        Map<String, String> properties = currentOnly(newPair());
        properties.put(PREVIOUS_PUBLIC_PROPERTY, encode(newPair().getPublic().getEncoded()));

        assertRejectedNaming(properties, PREVIOUS_KID_PROPERTY, "");
    }

    @Test
    void aPreviousPublicKeyThatIsNotBase64IsRejectedWithoutEchoingIt() {
        Map<String, String> properties = withPrevious(currentOnly(newPair()), newPair());
        properties.put(PREVIOUS_PUBLIC_PROPERTY, NOT_BASE64);

        assertRejectedNaming(properties, PREVIOUS_PUBLIC_PROPERTY, NOT_BASE64);
    }

    @Test
    void aPreviousKeyThatCarriesAPrivateKeyIsRejectedNamingItAndNeverEchoingIt() {
        KeyPair previous = newPair();
        Map<String, String> properties = withPrevious(currentOnly(newPair()), previous);
        String privateKey = encode(previous.getPrivate().getEncoded());
        properties.put(PREVIOUS_PRIVATE_PROPERTY, privateKey);

        assertRejectedNaming(properties, PREVIOUS_PRIVATE_PROPERTY, privateKey);
    }

    @Test
    void thePreviousKeyOfALoadedRingNeverHoldsAPrivateKey() {
        SigningKeyRing ring = SigningKeyRing.fromEnvironment(
                environment(withPrevious(currentOnly(newPair()), newPair())));

        assertThat(ring.keyForHeaderSegment(JwsFixtures.b64(JwsFixtures.canonicalHeaderJson(PREVIOUS_KID)))
                .map(SigningKey::hasPrivateKey)).hasValue(false);
    }

    private static void assertRejectedNaming(Map<String, String> properties, String property,
            String value) {
        assertThatThrownBy(() -> SigningKeyRing.fromEnvironment(environment(properties)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(property)
                .hasNoCause()
                .satisfies(failure -> {
                    for (int length = 4; length <= value.length(); length++) {
                        for (int start = 0; start + length <= value.length(); start++) {
                            assertThat(failure.getMessage())
                                    .as("a fragment of the rejected value")
                                    .doesNotContain(value.substring(start, start + length));
                        }
                    }
                });
    }

    private static Map<String, String> currentOnly(KeyPair current) {
        Map<String, String> properties = new LinkedHashMap<>();
        properties.put(CURRENT_KID_PROPERTY, CURRENT_KID);
        properties.put(CURRENT_PRIVATE_PROPERTY, encode(current.getPrivate().getEncoded()));
        properties.put(CURRENT_PUBLIC_PROPERTY, encode(current.getPublic().getEncoded()));
        return properties;
    }

    private static Map<String, String> withPrevious(Map<String, String> properties, KeyPair previous) {
        properties.put(PREVIOUS_KID_PROPERTY, PREVIOUS_KID);
        properties.put(PREVIOUS_PUBLIC_PROPERTY, encode(previous.getPublic().getEncoded()));
        return properties;
    }

    private static byte[] utf8(String text) {
        return text.getBytes(StandardCharsets.UTF_8);
    }

    private static String encode(byte[] der) {
        return Base64.getEncoder().encodeToString(der);
    }

    private static StandardEnvironment environment(Map<String, String> properties) {
        StandardEnvironment environment = new StandardEnvironment();
        environment.getPropertySources().addFirst(
                new MapPropertySource("signing-key-ring-test", new LinkedHashMap<>(properties)));
        return environment;
    }
}
