package com.confia.bootstrap;

import static com.confia.bootstrap.BootFailureAssertions.assertNoSecretFragment;
import static com.confia.bootstrap.BootFailureAssertions.chainOf;
import static com.confia.bootstrap.BootFailureAssertions.stackTraceOf;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.confia.bootstrap.ConfiaApplication.LaunchOutcome;
import com.confia.shared.security.AuthenticationMethod;
import com.confia.shared.security.token.AccessToken;
import com.confia.shared.security.token.AccessTokenIssuer;
import com.confia.shared.security.token.AccessTokenVerifier;
import com.confia.shared.security.token.SigningKeyRing;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.context.ConfigurableApplicationContext;

/**
 * Specs/identity, scenarios I81 to I84 and I140, and specs/build-integrity, BI28: each process, started
 * through the production launcher and without Docker, checks its own signing keys before the context is
 * created (ADR-0005, check 14; design.md decision 3 and D-N2). The administrative process starts with
 * a pair generated by the test and refuses to start without it; the portal and the worker refuse to
 * start when the administrative private key is in their environment; the administrative process
 * refuses to start when the name reserved for the portal's private key is in its own. A refusal
 * names the property and repeats no part of the value. The value is a marker of symbols no message
 * of the code could contain and no key, so a fragment of it in the trace is a leak.
 */
class SigningKeyStartupTest {

    private static final String GUARD = "SigningKeyPlacementGuard";

    /** Not a secret and not a key: symbols, so that a fragment found in a trace can only come from it. */
    private static final String MARKER = "Qx7!Rk2#Jv9%Wm5@";

    @ParameterizedTest
    @ValueSource(strings = {TestProcessArguments.CURRENT_KID_PROPERTY,
            TestProcessArguments.CURRENT_PRIVATE_KEY_PROPERTY,
            TestProcessArguments.CURRENT_PUBLIC_KEY_PROPERTY})
    void theAdministrativeProcessWithoutItsKeyDoesNotStartAndNamesTheProperty(String property) {
        assertThatThrownBy(() -> launch("admin", TestProcessArguments.adminWithout(property)))
                .satisfies(failure -> {
                    assertThat(stackTraceOf(failure)).contains(property);
                    assertThat(chainOf(failure)).anyMatch(IllegalStateException.class::isInstance);
                    assertNoSecretFragment(failure, "");
                });
    }

    @Test
    void theAdministrativeProcessStartsWithAKeyGeneratedByTheTestAndHoldsItInItsRing() {
        LaunchOutcome outcome = launch("admin", TestProcessArguments.forProcess("admin"));
        try {
            assertThat(outcome.context()).isNotNull();
            SigningKeyRing ring = outcome.context().getBean(SigningKeyRing.class);
            assertThat(ring.signingKey().kid()).isEqualTo(TestProcessArguments.SIGNING_KID);
            assertThat(ring.signingKey().hasPrivateKey()).isTrue();
        } finally {
            close(outcome.context());
        }
    }

    /** Task 1.4: the issuer and the verifier are beans of the administrative process, on its own ring. */
    @Test
    void theAdministrativeProcessHoldsAnIssuerAndAVerifierThatAgreeOnItsRing() {
        LaunchOutcome outcome = launch("admin", TestProcessArguments.forProcess("admin"));
        try {
            AccessTokenIssuer issuer = outcome.context().getBean(AccessTokenIssuer.class);
            AccessTokenVerifier verifier = outcome.context().getBean(AccessTokenVerifier.class);
            UUID account = UUID.randomUUID();
            UUID session = UUID.randomUUID();

            AccessToken token = issuer.issueAccess(account, UUID.randomUUID(), session,
                    EnumSet.of(AuthenticationMethod.PASSWORD));

            assertThat(verifier.verifyAccess(token.compact()).sessionId()).isEqualTo(session);
            assertThat(verifier.verifyAccess(token.compact()).accountId()).isEqualTo(account);
        } finally {
            close(outcome.context());
        }
    }

    @Test
    void theAdministrativeProcessStartsWithAPreviousPublicKeyAndHoldsBothInItsRing() {
        Map<String, String> overrides = new LinkedHashMap<>();
        overrides.put(TestProcessArguments.PREVIOUS_KID_PROPERTY, "test-admin-previous");
        overrides.put(TestProcessArguments.PREVIOUS_PUBLIC_KEY_PROPERTY,
                TestProcessArguments.newPublicKey());
        LaunchOutcome outcome = launch("admin", TestProcessArguments.adminWith(overrides));
        try {
            SigningKeyRing ring = outcome.context().getBean(SigningKeyRing.class);
            assertThat(ring.signingKey().kid()).isEqualTo(TestProcessArguments.SIGNING_KID);
            assertThat(ring.keyForHeaderSegment(headerSegmentOf("test-admin-previous"))
                    .map(key -> key.hasPrivateKey())).hasValue(false);
        } finally {
            close(outcome.context());
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"portal", "worker"})
    void theOtherProcessesStartWithoutTheKeyAndHoldNoRing(String process) {
        LaunchOutcome outcome = launch(process, TestProcessArguments.forProcess(process));
        try {
            assertThat(outcome.context()).isNotNull();
            assertThat(outcome.context().getBeansOfType(SigningKeyRing.class))
                    .as("no signing key ring in the %s process", process).isEmpty();
            assertThat(outcome.context().getBeansOfType(AccessTokenIssuer.class))
                    .as("no token issuer in the %s process", process).isEmpty();
            assertThat(outcome.context().getBeansOfType(AccessTokenVerifier.class))
                    .as("no token verifier in the %s process", process).isEmpty();
        } finally {
            close(outcome.context());
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"portal", "worker"})
    void theOtherProcessesAbortWhenTheCurrentAdministrativePrivateKeyIsPresent(String process) {
        assertAbortsBeforeTheContext(process,
                TestProcessArguments.CURRENT_PRIVATE_KEY_PROPERTY);
    }

    @ParameterizedTest
    @ValueSource(strings = {"portal", "worker"})
    void theOtherProcessesAbortWhenThePreviousAdministrativePrivateKeyIsPresent(String process) {
        assertAbortsBeforeTheContext(process,
                TestProcessArguments.PREVIOUS_PRIVATE_KEY_PROPERTY);
    }

    @ParameterizedTest
    @ValueSource(strings = {TestProcessArguments.PORTAL_CURRENT_PRIVATE_KEY_PROPERTY,
            TestProcessArguments.PORTAL_PREVIOUS_PRIVATE_KEY_PROPERTY})
    void theAdministrativeProcessAbortsWhenTheReservedPortalPrivateKeyNameIsPresent(
            String property) {
        String value = MARKER;

        assertThatThrownBy(() -> launch("admin", TestProcessArguments.adminWith(property, value)))
                .satisfies(failure -> {
                    assertThat(stackTraceOf(failure)).contains(property).contains(GUARD);
                    assertNoSecretFragment(failure, value);
                });
    }

    @Test
    void withoutTheReservedNamesTheAdministrativeProcessStartsAndLoadsNothingFromThem() {
        LaunchOutcome outcome = launch("admin", TestProcessArguments.forProcess("admin"));
        try {
            SigningKeyRing ring = outcome.context().getBean(SigningKeyRing.class);
            assertThat(ring.signingKey().kid()).isEqualTo(TestProcessArguments.SIGNING_KID);
            assertThat(outcome.context().getBeansOfType(SigningKeyRing.class)).hasSize(1);
        } finally {
            close(outcome.context());
        }
    }

    @ParameterizedTest
    @MethodSource("privateKeysThatAreNotAnEd25519Key")
    void theAdministrativeProcessAbortsOnAPrivateKeyThatIsNotAnEd25519KeyAndRepeatsNothingOfIt(
            String value) {
        assertThatThrownBy(() -> launch("admin", TestProcessArguments.adminWith(
                TestProcessArguments.CURRENT_PRIVATE_KEY_PROPERTY, value)))
                .satisfies(failure -> {
                    assertThat(stackTraceOf(failure))
                            .contains(TestProcessArguments.CURRENT_PRIVATE_KEY_PROPERTY);
                    assertNoSecretFragment(failure, value);
                });
    }

    static Stream<String> privateKeysThatAreNotAnEd25519Key() {
        return Stream.of(TestProcessArguments.base64ThatIsNotAKey(),
                TestProcessArguments.ed448ShapedPrivateKeyBase64());
    }

    private static void assertAbortsBeforeTheContext(String process, String property) {
        String value = MARKER;

        assertThatThrownBy(() -> launch(process,
                TestProcessArguments.forProcess(process, "--" + property + "=" + value)))
                .satisfies(failure -> {
                    assertThat(stackTraceOf(failure)).contains(property).contains(GUARD);
                    assertNoSecretFragment(failure, value);
                });
    }

    private static LaunchOutcome launch(String process, String[] arguments) {
        return ConfiaApplication.launch(arguments, process);
    }

    private static String headerSegmentOf(String kid) {
        String header = "{\"alg\":\"EdDSA\",\"kid\":\"" + kid + "\"}";
        return java.util.Base64.getUrlEncoder().withoutPadding()
                .encodeToString(header.getBytes(java.nio.charset.StandardCharsets.US_ASCII));
    }

    private static void close(ConfigurableApplicationContext context) {
        if (context != null) {
            context.close();
        }
    }
}
