package com.confia.bootstrap;

import static com.confia.bootstrap.BootFailureAssertions.assertNoSecretFragment;
import static com.confia.bootstrap.BootFailureAssertions.chainOf;
import static com.confia.bootstrap.BootFailureAssertions.stackTraceOf;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.confia.bootstrap.ConfiaApplication.LaunchOutcome;
import com.confia.shared.security.token.SigningKeyRing;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.context.ConfigurableApplicationContext;

/**
 * Specs/identity, scenarios I81, I82 and I84, and specs/build-integrity, BI28: the administrative process,
 * started through the production launcher and without Docker, starts with a pair generated by the test
 * and refuses to start without it (ADR-0005, check 14; design.md decision 3). A refusal names the
 * property and repeats no part of the value.
 */
class SigningKeyStartupTest {

    @ParameterizedTest
    @ValueSource(strings = {TestProcessArguments.CURRENT_KID_PROPERTY,
            TestProcessArguments.CURRENT_PRIVATE_KEY_PROPERTY,
            TestProcessArguments.CURRENT_PUBLIC_KEY_PROPERTY})
    void theAdministrativeProcessWithoutItsKeyDoesNotStartAndNamesTheProperty(String property) {
        assertThatThrownBy(() -> launch("admin", TestProcessArguments.adminWithout(property)))
                .satisfies(failure -> {
                    assertThat(stackTraceOf(failure)).contains(property);
                    assertThat(chainOf(failure)).anyMatch(IllegalStateException.class::isInstance);
                    assertNoSecretFragment(failure, "");
                });
    }

    @Test
    void theAdministrativeProcessStartsWithAKeyGeneratedByTheTestAndHoldsItInItsRing() {
        LaunchOutcome outcome = launch("admin", TestProcessArguments.forProcess("admin"));
        try {
            assertThat(outcome.context()).isNotNull();
            SigningKeyRing ring = outcome.context().getBean(SigningKeyRing.class);
            assertThat(ring.signingKey().kid()).isEqualTo(TestProcessArguments.SIGNING_KID);
            assertThat(ring.signingKey().hasPrivateKey()).isTrue();
        } finally {
            close(outcome.context());
        }
    }

    @Test
    void theAdministrativeProcessStartsWithAPreviousPublicKeyAndHoldsBothInItsRing() {
        Map<String, String> overrides = new LinkedHashMap<>();
        overrides.put(TestProcessArguments.PREVIOUS_KID_PROPERTY, "test-admin-previous");
        overrides.put(TestProcessArguments.PREVIOUS_PUBLIC_KEY_PROPERTY,
                TestProcessArguments.newPublicKey());
        LaunchOutcome outcome = launch("admin", TestProcessArguments.adminWith(overrides));
        try {
            SigningKeyRing ring = outcome.context().getBean(SigningKeyRing.class);
            assertThat(ring.signingKey().kid()).isEqualTo(TestProcessArguments.SIGNING_KID);
            assertThat(ring.keyForHeaderSegment(headerSegmentOf("test-admin-previous"))
                    .map(key -> key.hasPrivateKey())).hasValue(false);
        } finally {
            close(outcome.context());
        }
    }

    private static LaunchOutcome launch(String process, String[] arguments) {
        return ConfiaApplication.launch(arguments, process);
    }

    private static String headerSegmentOf(String kid) {
        String header = "{\"alg\":\"EdDSA\",\"kid\":\"" + kid + "\"}";
        return java.util.Base64.getUrlEncoder().withoutPadding()
                .encodeToString(header.getBytes(java.nio.charset.StandardCharsets.US_ASCII));
    }

    private static void close(ConfigurableApplicationContext context) {
        if (context != null) {
            context.close();
        }
    }
}
