package com.confia.identity.application;

import com.confia.identity.domain.RecoveryCodeRow;
import com.confia.identity.domain.StaffAccountId;
import com.confia.identity.domain.StoredRecoveryCodeHash;
import com.confia.kernel.InstitutionId;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Reads and writes {@code identity_mfa_recovery_code}'s rows (column-encryption-and-mfa-totp
 * design.md, decision 3, §4.1, §4.3). {@link com.confia.identity.infrastructure.JooqRecoveryCodeRepository}
 * is its single jOOQ adapter.
 */
public interface RecoveryCodeRepository {

    /**
     * Inserts one row for a newly enrolled account, {@code hash} already hashed by {@link
     * RecoveryCodeHasher} — this port never hashes or verifies anything itself (the same split
     * {@link TotpCredentialRepository#insert} already applies to encryption). {@code id} is the
     * row's own primary-key component, generated by the caller (design.md, §4.1).
     */
    void insert(InstitutionId institutionId, StaffAccountId accountId, UUID id,
            StoredRecoveryCodeHash hash);

    /** The account's not-yet-used codes, each with its own row id to mark used on a match
     * (design.md, §4.3, steps 1-2). */
    List<RecoveryCodeRow> findUnusedByAccountId(InstitutionId institutionId, StaffAccountId accountId);

    /**
     * The conditional consumption design.md §4.3 step 3 fixes exactly: {@code UPDATE ... SET
     * used_at = now() WHERE id = ? AND used_at IS NULL RETURNING id}. Returns {@code true} when
     * the update affected the row, {@code false} when it affected zero rows — the signal that a
     * concurrent consumption already won this exact code, the same defeat {@link
     * TotpCredentialRepository#acceptCounter} already treats as a rejection for its own contested
     * case.
     */
    boolean markUsed(InstitutionId institutionId, UUID id, Instant usedAt);

    /** The account's remaining unused-code count, read after a successful consumption (design.md,
     * §4.3, step 5). */
    long countUnusedByAccountId(InstitutionId institutionId, StaffAccountId accountId);
}
